const data=[{'component': '<PythonSlicingdataframe />', 'path': '', 'title': '3'},
{'component': '<PythonReplacingvalues />', 'path': '', 'title': '5'},
{'component': '<PythonRenamingcolumns />', 'path': '', 'title': '6'},
{'component': '<PythonGroupingrowsbyvalues />', 'path': '', 'title': '12'},
{'component': '<PythonMissingvalues />', 'path': '', 'title': '9'},
{'component': '<PythonConcatenatedataframes />', 'path': '', 'title': '15'},
{'component': '<PythonMinmaxsummeancount />', 'path': '', 'title': '7'},
{'component': '<PythonDroppingduplicaterows />', 'path': '', 'title': '11'},
{'component': '<PythonLoadingdataintopandasdataframe />', 'path': '', 'title': '1'},
{'component': '<PythonUniquevalues />', 'path': '', 'title': '8'},
{'component': '<PythonDeletingcolumnsrows />', 'path': '', 'title': '10'},
{'component': '<PythonMergingdataframes />', 'path': '', 'title': '14'},
{'component': '<PythonOpeningstatement />', 'path': '', 'title': '0'},
{'component': '<PythonSortingvalues />', 'path': '', 'title': '4'},
{'component': '<PythonApplycustomfunction />', 'path': '', 'title': '13'},
{'component': '<PythonGettinginformationaboutdata />', 'path': '', 'title': '2'},
]