const data=[{'component': '<PythonLoopcontrolstatements />', 'path': 'python-loop-control-statements', 'title': 'Loop Control Statements'},
{'component': '<PythonInstallingjupyternotebook />', 'path': 'python-installing-jupyter-notebook', 'title': 'Installing Jupyter Notebook'},
{'component': '<PythonDatastructureslists />', 'path': 'python-data-structures-lists', 'title': 'Data Structures Lists'},
{'component': '<PythonForloops />', 'path': 'python-forloops', 'title': 'forloops'},
{'component': '<PythonOperationscomparison />', 'path': 'python-operations-comparison', 'title': 'Operations Comparison'},
{'component': '<PythonFunctionsdefinitionandparameters />', 'path': 'python-functions-definitionand-parameters', 'title': 'Functions Definitionand Parameters'},
{'component': '<PythonPythonbasicslandingpage />', 'path': 'python-python-basics-landing-page', 'title': 'Python Basics Landing Page'},
{'component': '<PythonOopclassesandobjects />', 'path': 'python-o-o-p-classes-and-objects', 'title': 'O O P Classes And Objects'},
{'component': '<PythonModulesandlibraries  />', 'path': 'python-modules-and-libraries ', 'title': 'Modules And Libraries '},
{'component': '<PythonDatastructurestuples />', 'path': 'python-data-structures-tuples', 'title': 'Data Structures Tuples'},
{'component': '<PythonFunctionslambdafunctions />', 'path': 'python-functions-lambda-functions', 'title': 'Functions Lambda Functions'},
{'component': '<PythonFunctionslocalvariableandglobalvariable />', 'path': 'python-functions-local-variableand-global-variable', 'title': 'Functions Local Variableand Global Variable'},
{'component': '<PythonVariables />', 'path': 'python-variables', 'title': 'Variables'},
{'component': '<PythonOperationslogical />', 'path': 'python-operations-logical', 'title': 'Operations Logical'},
{'component': '<PythonPrintmethod />', 'path': 'python-print-method', 'title': 'Print Method'},
{'component': '<PythonOperationsarithmetic />', 'path': 'python-operations-arithmetic', 'title': 'Operations Arithmetic'},
{'component': '<PythonInstallingpython />', 'path': 'python-installing-python', 'title': 'Installing Python'},
{'component': '<PythonWhileloop />', 'path': 'python-while-loop', 'title': 'While Loop'},
{'component': '<PythonFunctionsreturnstatements />', 'path': 'python-functions-return-statements', 'title': 'Functions Return Statements'},
{'component': '<PythonIntroductiontopython />', 'path': 'python-introduction-to-python', 'title': 'Introduction To Python'},
{'component': '<PythonDatastructuresdictionaries />', 'path': 'python-data-structures-dictionaries', 'title': 'Data Structures Dictionaries'},
{'component': '<PythonClassinheritance />', 'path': 'python-class-inheritance', 'title': 'Class Inheritance'},
{'component': '<PythonIfelse />', 'path': 'python-if-else', 'title': 'If Else'},
{'component': '<PythonDatastructuressets />', 'path': 'python-data-structures-sets', 'title': 'Data Structures Sets'},
]